### ISSUE TITLE
Return 202 and no errors are logged, but not SSL binding

### ISSUE THREAD

**Issue by changeworld** [shibayan/azure-appservice-letsencrypt#17]
I have just deployed the Function via the Deploy to Azure Button and tried AddCertificate_HttpStart.
I always get af 202 and "[Information] Started orchestration with ID = 'xxx'. [Information] Executed 'AddCertificate_HttpStart' (Succeeded, Id=xxx)".
But, waiting for hours no SSL binding will be done.
I thought that the values ​​of ResourceGroupName, SiteName, and Domain were wrong, I rewritten it to a nonexistent value and executed it, but the result was the same.
I have looked trough README.md but I can't seem to find why and where this is a problem.

**Comment by shibayan** [comment]
Please check `AddCertificate` Azure Function monitor. I think that an error log is output to Invocation Details.

![image](https://user-images.githubusercontent.com/1356444/44648269-7c3cd300-aa1b-11e8-8147-d2cc47cb53ff.png)

**Comment by changeworld** [comment]
I checked AddCertificate Azure Function monitor.
The following error was output to the log.

`(省略)Function 'AddCertificate (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.FunctionFailedException: The activity function 'GetSite' failed: "Failed to deserialize exception from TaskActivity: {"Request":{"Method":{"Method":"GET"},"RequestUri":"[URL]"(省略)`

When I access [URL] via browser, the following is displayed.

```{"error":{"code":"AuthenticationFailed","message":"認証が失敗しました。'Authorization' ヘッダーが見つかりません。"}}```

In case of this error, would you please tell me what value is missing or incorrect?

**Comment by changeworld** [comment]
I'm sorry. I was looking at the locally cloned README.md, but in the latest README.md there was one IAM that I had written to grant.
`IAM settings may take time to be activated. As it is about Azure's cache.`, so, after setting, wait for about a day and try to check whether it will reoccur.
