### ISSUE TITLE
How to add params to AddCertificate_HttpStart

### ISSUE THREAD

**Issue by shyamal890** [shibayan/azure-appservice-letsencrypt#21]
When I click on the `AddCertificate_HttpStart` function it says the function is read-only how to solve this? How to add the needed params?

Also to generate wildcard certificate should the `domain` be something like `*.example.com` ?

**Comment by shibayan** [comment]
Function is read-only normally.
To execute from Azure Portal, you can set parameters by opening "Test".

![image](https://user-images.githubusercontent.com/1356444/44954578-eef7f380-aede-11e8-9b5a-159223786b00.png)

If you use a wildcard certificate, you need to create an Azure DNS zone for example.com and add *.example.com to App Service.

**Comment by shyamal890** [comment]
Is there a way I can add multiple sites to one request?

**Comment by shibayan** [comment]
Now AddCertificate_HttpStart support one site with one request. Please execute as any requests as you need.

**Comment by shyamal890** [comment]
I am getting "*.example.com" not found error in the AddCertificate logs.

**Comment by shibayan** [comment]
Please open Monitor and try opening the latest log. Notice that a few minutes of lag will occur from the time it is executed until it is displayed.

![image](https://user-images.githubusercontent.com/1356444/44955152-d93bfb80-aee9-11e8-87bb-6aa2210f94b2.png)

Note that due to a problem on the Function Runtime side, even if it fails, it is displayed as success.

**Comment by shibayan** [comment]
This domain been added to App Service?
The error occurs when a custom host name added to App Service can not be found.

**Comment by shyamal890** [comment]
Yes the domain is already added to App Service.

**Comment by shibayan** [comment]
Please check hostNameSslStates of App Service you are trying to add using Resource Explorer.
https://resources.azure.com/

And your domain does not seem to be managed by Azure DNS. Azure DNS is required to issue wild card certificates.

**Comment by shyamal890** [comment]
Ohk so my domains should be hosted by Azure for this to work. What if my domain is being hosted by Namecheap.com ?

**Comment by shibayan** [comment]
Since it is necessary to add CNAME record to DNS to issue wildcard certificate, it can not be issued except Azure DNS.
