### ISSUE TITLE
Need notification of updated

### ISSUE THREAD

**Issue by k-miyake** [shibayan/azure-appservice-letsencrypt#34]
I think we need the option to be sent e-mail notification when the certificate is actually updated.

**Comment by k-miyake** [comment]
I think that it is enough we can detect events as webhook.

**Comment by k-miyake** [comment]
For example, it is enough to detect events and publish Webhook.
https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-event-publishing

**Comment by jacobmohl** [comment]
I would be nice to be able to hook a Logic App (through an event). So it can be Emails, Teams or whatever tool you would like the notification to be in.
