### ISSUE TITLE
Error: Request failed with status code 401 I tried the add Certificate in function

### ISSUE THREAD

**Issue by lfogaca43** [shibayan/azure-appservice-letsencrypt#46]
I have also implemented the function and tried the AddCertificate. But always displays an error Error: Request failed with status code 401.
In  function Authentication / Authorization from Azure Portal and turn on App Service Authentication. Then select Log in with as Anonymous access is enabled on the App Service app, that's right?
I have looked trough your code but can´t seem to find why and where this is a problem.
Can you help?

Thanks

Leonardo Almeida

**Comment by shibayan** [comment]
Please confirm again whether you set Azure Active Directory settings from Azure Portal according to README.

https://github.com/shibayan/azure-appservice-letsencrypt/blob/master/README.md#3-enable-app-service-authentication-easyauth-with-aad

Anonymous authentication is not allowed. Login is required when displaying the Web UI.

**Comment by lfogaca43** [comment]
Ok now it worked, but did not display the custom environment that is a linux container that is enabled ssl binding SNI, can it help again?

Thanks

**Comment by shibayan** [comment]
If the certificate has already been bound, it will not be displayed in the list.

Rel #44

**Comment by lfogaca43** [comment]
OK,
Another doubt, in case I remove the certificate your code issues a Wildcart certificate

Thanks again.

**Comment by shibayan** [comment]
Azure DNS is required to issue wild card certificates. It is necessary to check the setting of IAM and DNS zone.

**Comment by lfogaca43** [comment]
Ok Thanks very much

**Comment by sabbour** [comment]
@shibayan does this really require setting up Authentication/Authorization? I thought it can work with Managed Service Identity.
The reason I'm asking is, I don't have admin access on my organization AD so I can't approve the application.

**Comment by shibayan** [comment]
@sabbour AuthN / AuthZ is necessary only for the Web UI, so it is possible to run with MSI.

Only need to set EasyAuth, it should work with providers other than AAD.
(twitter / facebook / etc...)

If you have a good idea, please suggest it.
