### ISSUE TITLE
Remove Azure DNS Zone requirement for App Services on Linux

### ISSUE THREAD

**Issue by anton-dealmeida** [shibayan/azure-appservice-letsencrypt#52]
Hi there,

So, I am trying to make use of this LetsEncrypt with Azure App Services on Linux. However, we do not wish to move our DNS zone / names to Azure DNS. Is there a way to use this function without being stuck to using DNS zone?

`Orchestrator function 'AddCertificate' failed: The activity function 'Dns01Precondition' failed: "Azure DNS zone "<my_app_name>.trafficmanager.net" is not found". See the function execution logs for additional details.`

I have a traffic manager located in front of my apps as well because I'm playing with geo-redundancy and for some odd reason this makes the function pick up the trafficmanager.net URL which is fine but I can't verify that either.

**Comment by shibayan** [comment]
App Service on Linux does not have the API required for HTTP-01 authentication of Let's Encrypt, authentication with DNS is essential.

There are currently no plans to support providers other than Azure DNS.

Trying to see the domain of Traffic Manager is a bug, so I will fix it separately. Thanks.
