### ISSUE TITLE
Dropdowns empty / API with status 200 when spawned in non-default directory

### ISSUE THREAD

**Issue by sanket-t-shah** [shibayan/azure-appservice-letsencrypt#55]
I've deployed the resources via your script into my non-default subscription. When I try to access the URL, it asks me for credentials. Post that, all dropdowns are blank, but API status is 200. Any hints on how to solve the problem?

**Comment by shibayan** [comment]
IAM setting check required

**Comment by sanket-t-shah** [comment]
Did that - any way you can help me in the same?

**Comment by shibayan** [comment]
Requires App Service without SSL certificate bound.
It is not displayed even if custom domain is not assigned.

**Comment by ffcruz85** [comment]
@shibayan per your last comment - do you meant that if I have a web app currently deployed with certificates and custom domains, the dropdowns will not populate? I should first remove the domains and re-add them?
