### ISSUE TITLE
Error creating wildcard certificate 

### ISSUE THREAD

**Issue by lfogaca43** [shibayan/azure-appservice-letsencrypt#63]
Hello Shibayan, How are you?
Are you displaying an error message in the application application Insight below, how do I solve this problem?
Exception while executing function: CheckDnsChallenge <--- _acme-challenge.infraestruturameioambiente.sp.gov.br did not resolve.

Regards

**Comment by shibayan** [comment]
`CheckDnsChallenge` will retry several times in case of error. If a certificate has been issued, this is an error that can be ignored.

If you continue to fail to issue a certificate, I will be asked to provide more information.

**Comment by lfogaca43** [comment]
Ok, now the certificate has been issued.

Another doubt I can copy this wilcard certificate issued to a test vm in azure?
