### ISSUE TITLE
Display all certificat that are not from let's encrypt

### ISSUE THREAD

**Issue by JeremyJeanson** [shibayan/azure-appservice-letsencrypt#68]
It could be fine if the Web UI could display certificat from others CA than Let's encrypt. And add abilty to replace them.

Prior to use this extension, i had to remove all my certificats (for a short period of time, my apps had non certificat).

**Comment by shibayan** [comment]
I modified the Web UI to make it replaceable.

**Comment by JeremyJeanson** [comment]
Thank you ;)

**Comment by JaapMosselman** [comment]
That's nice! But it also shows the bindings which are already from Let's Encrypt. That's not so helpfull for the overview.
(Allthough another view with all the Let's Encrypt bindings whould be nice, just a simple list)
