### ISSUE TITLE
Export an App Service certificate  to a pfx file with PowerShell

### ISSUE THREAD

**Issue by lfogaca43** [shibayan/azure-appservice-letsencrypt#74]
Hello Shibayan,
Can I export the certificate after it is created in a local folder on my server?
I found this article "https://benohead.com/export-app-service-certificate-pfx-file-powershell/" but displays an error below:
The Resource 'Microsoft.Web / certificates / xxxxx "under resource group' Letencrypt 'was not found

Thanks for the help

**Comment by shibayan** [comment]
PFX export is not possible because it is different from App Service Certificate.
If you need to export, you need to use the Key Vault version. https://github.com/shibayan/azure-keyvault-letsencrypt

**Comment by lfogaca43** [comment]
Ok Shibayan,

Thanks for the help.
