### ISSUE TITLE
Unable to use certificate for signing purpose

### ISSUE THREAD

**Issue by hugoterelle** [shibayan/azure-appservice-letsencrypt#76]
Following this stackoverflow post I created here: 
https://stackoverflow.com/questions/56042897/unable-to-use-lets-encrypt-certificate-into-azure-web-app

I wondering if there is any problem concerning the type of certificate created with Letsencrypt.
Why it's not possible to receive an RSA/DSA certificate?

I tried to use a certificate generated by Letsencrypt using another tool (https://certifytheweb.com/) and the exported certificate is working with my code.

Btw, why there is no password to secure the certificate generated by your tool?
Sorry for my questions but I'm not an expert in certificates management.

**Comment by shibayan** [comment]
Signing is not possible because it is different from App Service Certificate.
If you need to export, you need to use the Key Vault version. https://github.com/shibayan/azure-keyvault-letsencrypt
