### ISSUE TITLE
Error renewing certificate

### ISSUE THREAD

**Issue by lfogaca43** [shibayan/azure-appservice-letsencrypt#79]
Hi Shibamura,

This is displaying an error when renewing the certificate in function Renew Certificate, I am worried because the certificate expires on June 7th. Could you help please?

Here are the logs that I collected:
![Error Renewing Certificate](https://user-images.githubusercontent.com/20261000/58286740-caea8400-7d85-11e9-9919-4b44c216d4c3.PNG)
![Error Renewing Certificate2](https://user-images.githubusercontent.com/20261000/58286756-d50c8280-7d85-11e9-8612-e840a5065133.PNG)

Every help is welcome

**Comment by VaclavElias** [comment]
What kind of blurring you used :) try Windows 10 Snip & Sketch :)

@shibayan I also wonder if there is any easy way to health check that all is ok. Not sure if it is mentioned in your documentation or there is any function which would tell me the health.

Or shall we just check Application Insights for any error which would lead us to the finding like e.g. above that CheckDnsChallange is not working?

**Comment by shibayan** [comment]
@lfogaca43 Normally, the update should be completed 30 days ago, so it will not be updated correctly.
I need information to solve the problem. Open Azure DNS settings and tell us the TTL of the records starting with `_acme-challenge`.

@VaclavElias Now It functions provide a webhook, It can notify Slack on failure.
Since CheckDnsChallenge etc. is designed to be retried, it is necessary to check RenewCertificates and AddCertificate for health check.

**Comment by VaclavElias** [comment]
Thank you for info @shibayan

**Comment by lfogaca43** [comment]
OKAY @shibayan I change my Azure DNS settings to Force DNS TTL to 60s. 

I'll be monitoring

**Comment by lfogaca43** [comment]
Hi Shibamura,

Another error: Other Orchestrator function 'RenewCertificates' failed
![Error RenewSiteCerticater](https://user-images.githubusercontent.com/20261000/58340426-397d1f80-7e22-11e9-85f5-a5af30436f37.PNG)
Can you help again?

Thanks

**Comment by shibayan** [comment]
@lfogaca43 The error is due to the rate limit of Let's Encrypt.
Wait for rate limit to be released, or delete "D:\home\.acme" for resolution (recommended only in emergency situations)

**Comment by lfogaca43** [comment]
Thank you for info @shibayan

**Comment by lfogaca43** [comment]
@shibayan 
![Error RenewSiteCertificate](https://user-images.githubusercontent.com/20261000/58350435-40b12700-7e3c-11e9-85bd-f84ff7a2fa60.PNG)

Answer a question, please.

I got this error now, where do I look for more detail of this event?
