### ISSUE TITLE
New certificate generation not working - Throwing error 500

### ISSUE THREAD

**Issue by alexpilon666** [shibayan/azure-appservice-letsencrypt#83]
Hello!

I installed and setup the function app, followed the documentation to enable authentication on the function app, etc., yet, when I access the `/add-certificate` to create my certificate, once I click the Submit button, it tries to generate the certificate, and returns an error 500.

My Web App is pretty standard: Linux Web App w/ S1 SKU. I have the standard Production deployment slot, with a secondary slot as well; Trying to deploy the certificate on the Production deployment slot, using SNI-based SSL, no IP-pased.

I'm not quite sure what extra information I could supply to help troubleshooting, so let me know if you need more info. I've tried looking for logs on both the function app, and my web app, and I see nothing whatsoever. 

As troubleshooting measures, I've removed all existing SSL certificates and bindings, just in case there was any conflict, and that didn't help.

Thanks in advance for the help!!

**Comment by alexpilon666** [comment]
Just went through the documentation again, and just noticed that Azure DNS is mandatory for App Service on Linux, which we're not using because we're not controlling the domain, our client is! :( 

Is there any technical reason as to why this is ? I mean, DNS is DNS in the end...

Thanks.

**Comment by shibayan** [comment]
For Linux App Service, the domain needs to be managed by Azure DNS as described in the README.

This is because verification using HTTP is very difficult with the Linux App Service. Windows App Service can use virtual applications, so it can only be done via HTTP.
