### ISSUE TITLE
Certificate XXX was not found

### ISSUE THREAD

**Issue by jacobmohl** [shibayan/azure-appservice-letsencrypt#9]
I have just deployed the Function and tried the AddCertificate. But i always get af "Certificate XX was not found" error. I have looked trough your code but can´t seem to find why and where this is a problem.

There is no certificates ind either the App Service or in the Storage account. Where should the Certificate be stored?

**Comment by shibayan** [comment]
@jacobmohl

Is Web App and App Service Plan in another Resource Groups?

**Comment by jacobmohl** [comment]
Yes. The Function, storsge ect. from your deploy link is in its own Resource Group and the app service plan and web app is in another.

**Comment by shibayan** [comment]
Currently, I'm working to solve the problem.

**Comment by shibayan** [comment]
Fixed. Please read again a README.md
